include: package:flutter_lints/flutter.yaml
 

linter:
  rules:
    - prefer_relative_imports
    - avoid_relative_lib_imports
    # - avoid_dynamic_calls
    - avoid_print
    - avoid_returning_null_for_future
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - collection_methods_unrelated_type
    - control_flow_in_finally
    - discarded_futures
    - empty_statements  
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - unsafe_html
    - use_key_in_widget_constructors
    # Styles 
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_require_non_null_named_parameters
    # - always_specify_types
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    # - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    # - avoid_final_parameters
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - conditional_uri_does_not_exist
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - dangling_library_doc_comments
    - deprecated_consistency
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - enable_null_safety
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - implementation_imports
    - implicit_call_tearoffs
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_annotations
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    - lines_longer_than_80_chars: false
    - missing_whitespace_between_adjacent_strings
    - no_default_cases
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - no_runtimeType_toString
    - non_constant_identifier_names
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - null_closures
    - omit_local_variable_types
    # - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_bool_in_asserts
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    # - prefer_final_parameters
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    # - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    # - public_member_api_docs
    - recursive_getters
    - require_trailing_commas
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - type_init_formals
    # - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_constructor_name
    # - unnecessary_final
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_library_directive
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - unreachable_from_main
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_string_in_part_of_directives
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    - void_checks

analyzer:
  language:
    strict-casts
    strict-inference
    strict-raw-types
  exclude:
    # Generated files
    - lib/**injector.config.dart
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.freezed.dart
  errors:
    # Mobx recommendations
    library_private_types_in_public_api: ignore 

    # Freezed and JsonSerializable recommendations
    invalid_annotation_target: ignore

    # Necessary until refactor all codes outside ```lib/src``` folder.
    deprecated_member_use_from_same_package: ignore
 
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    # TODO: Review metrics when removed all legacy code outside folder `lib/src`
    cyclometer-complexity: 20
    maximum-nesting-level: 10
    lines-of-code: 100
    source-lines-of-code: 100
    number-of-methods: 20
    number-of-parameters: 10
    # halstead-volume: 200
    # maintainability-index: 200
    # technical-debt:
    #   threshold: 1
    #   todo-cost: 161
    #   ignore-cost: 320
    #   ignore-for-file-cost: 396
    #   as-dynamic-cost: 322
    #   deprecated-annotations-cost: 37
    #   file-nullsafety-migration-cost: 41
    #   unit-type: "USD"
    # weight-of-class: 0.33
  metrics-exclude:
    # Generated files
    - lib/**injector.config.dart
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.freezed.dart
    - test/**.dart
    

  rules:
    # Commons
    - arguments-ordering:
      severity: error
    - avoid-banned-imports:
      severity: error
    - avoid-cascade-after-if-null:
      severity: error
    - avoid-collection-methods-with-unrelated-types:
      severity: error
    - avoid-double-slash-imports:
      severity: error
    - avoid-duplicate-exports:
      severity: error
    - avoid-dynamic:
      severity: error
    - avoid-global-state:
      severity: error
    - avoid-ignoring-return-values:
      severity: error
    - avoid-late-keyword:
      severity: error
    - avoid-missing-enum-constant-in-map:
      severity: error
    - avoid-nested-conditional-expressions:
      severity: error
    - avoid-non-ascii-symbols:
      severity: error
    - avoid-non-null-assertion:
      severity: error
    - avoid-passing-async-when-sync-expected:
      severity: error
    - avoid-redundant-async:
      severity: error
    - avoid-throw-in-catch-block:
      severity: error
    - avoid-top-level-members-in-tests:
      severity: error
    - avoid-unnecessary-conditionals:
      severity: error
    - avoid-unnecessary-type-assertions:
      severity: error
    - avoid-unnecessary-type-casts:
      severity: error
    - avoid-unrelated-type-assertions:
      severity: error
    - avoid-unused-parameters:
      severity: error
    - ban-name:
      severity: error
    - binary-expression-operand-order:
      severity: error
    - double-literal-format:
      severity: error
    - format-comment:
      severity: error
    - list-all-equatable-fields:
      severity: error
    - member-ordering:
        order:
          - constructors
          - public-fields
          - private-fields
          - close-method
          - dispose-method
        widgets-order:
          - constructor
          - build-method
          - init-state-method
          - did-change-dependencies-method
          - did-update-widget-method
          - dispose-method
        severity: error
    - missing-test-assertion:
      severity: error
    - newline-before-return:
      severity: error
    - no-boolean-literal-compare:
      severity: error
    - no-empty-block:
      severity: error
    - no-equal-arguments:
      severity: error
    - no-equal-then-else:
      severity: error
    - no-magic-number:
      severity: error
    - no-object-declaration:
      severity: error
    - prefer-async-await:
      severity: error
    - prefer-commenting-analyzer-ignores:
      severity: error
    - prefer-conditional-expressions:
      severity: error
    - prefer-correct-identifier-length:
      severity: error
    - prefer-correct-test-file-name:
      severity: error
    - prefer-correct-type-name:
      severity: error
    - prefer-enums-by-name:
      severity: error
    - prefer-first:
      severity: error
    - prefer-immediate-return:
      severity: error
    - prefer-iterable-of:
      severity: error
    - prefer-last:
      severity: error
    - prefer-match-file-name:
      severity: error
    - prefer-moving-to-variable:
      severity: error
    - prefer-static-class:
      severity: error
    - prefer-trailing-comma:
      severity: error
    # Flutter rules
    - always-remove-listener:
      severity: error
    - avoid-border-all:
      severity: error
    - avoid-expanded-as-spacer:
      severity: error
    - avoid-returning-widgets:
      severity: error
    - avoid-shrink-wrap-in-lists:
      severity: error
    - avoid-unnecessary-setstate:
      severity: error
    - avoid-wrapping-in-padding:
      severity: error
    - check-for-equals-in-render-object-setters:
      severity: error
    - consistent-update-render-object:
      severity: error
    - prefer-const-border-radius:
      severity: error
    - prefer-correct-edge-insets-constructor:
      severity: error
    - prefer-extracting-callbacks:
      severity: error
    - prefer-single-widget-per-file:
      severity: error
    - prefer-using-list-view:
      severity: error
    - use-setstate-synchronously:
      severity: error
    # intl
    - prefer-intl-name:
      severity: error
    - provide-correct-intl-args:
      severity: error

  rules-exclude:
    # Generated files
    - lib/**injector.config.dart
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.freezed.dart

  anti-patterns:
    - long-method:
      exclude:
        - test/*.dart
    - long-parameter-list:
      exclude:
        - test/*.dart
