name: custom_player_mentoria_tdd
 
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/go_router/install
  go_router: ^6.0.8

  # https://pub.dev/packages/get_it/install
  get_it: ^7.2.0

  # https://pub.dev/packages/injectable/install
  injectable: ^2.1.0

  # https://pub.dev/packages/freezed_annotation/install
  freezed_annotation: ^2.2.0

  # https://pub.dev/packages/google_fonts/install
  google_fonts: ^4.0.3

  # https://pub.dev/packages/logger/install
  logger: ^1.1.0

  # https://pub.dev/packages/provider/install
  provider: ^6.0.5

  # https://pub.dev/packages/dio/install
  dio: ^5.0.0

  # https://pub.dev/packages/json_annotation/install
  json_annotation: ^4.8.0

  # https://pub.dev/packages/flutter_mobx
  flutter_mobx: ^2.0.6

  # https://pub.dev/packages/mobx
  mobx: ^2.1.3
 
  # https://pub.dev/packages/freezed
  freezed: ^2.3.2

  # https://pub.dev/packages/fpdart/install
  fpdart: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

  # https://pub.dev/packages/build_runner/install
  build_runner: ^2.3.3

  # https://pub.dev/packages/injectable_generator
  injectable_generator: ^2.1.4

  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.6.1

  # https://pub.dev/packages/faker
  faker: ^2.1.0

  # https://pub.dev/packages/mocktail
  mocktail: ^0.3.0

  # https://pub.dev/packages/mobx_codegen
  mobx_codegen: ^2.1.1
  
  # https://pub.dev/packages/http_mock_adapter/
  http_mock_adapter: ^0.4.2
  dart_code_metrics: ^5.6.0
 
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true